ALTER TABLE "DeadLine" ADD COLUMN "startDate" TIMESTAMP(3),
ADD COLUMN "endDate" TIMESTAMP(3),
ADD COLUMN "recurrenceAnchor" TEXT NOT NULL DEFAULT 'DUE_DATE',
ADD COLUMN "workingDayAdjustment" TEXT NOT NULL DEFAULT 'NONE',
ADD COLUMN "dependsOnIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
ADD COLUMN "archivedAt" TIMESTAMP(3),
ADD COLUMN "archiveExempt" BOOLEAN NOT NULL DEFAULT false;

CREATE TABLE "AppSetting" ("key" TEXT NOT NULL, "value" TEXT NOT NULL, CONSTRAINT "AppSetting_pkey" PRIMARY KEY ("key"));
