import { promises as fs } from "fs";
import path from "path";
import type { Database } from "@/types";
import { createSeed } from "./seed";
import { CATEGORIES } from "./constants";
const file=path.join(process.cwd(),"data","local-db.json");
let queue=Promise.resolve();
async function readPostgres():Promise<Database>{const {prisma}=await import("./prisma");let users=await prisma.user.findMany();if(!users.length){const seed=createSeed();for(const u of seed.users)await prisma.user.create({data:{...u,passwordHash:"bootstrap-via-env"}});users=await prisma.user.findMany()}const deadlines=await prisma.deadLine.findMany({include:{auditLogs:{include:{actor:true},orderBy:{createdAt:"desc"}}}});const logs=await prisma.notificationLog.findMany({orderBy:{createdAt:"desc"},take:100});return{users:users.map(({passwordHash:_,...u})=>u),categories:CATEGORIES,notificationLog:logs.map(x=>({id:x.id,message:x.message,at:x.createdAt.toISOString()})),deadlines:deadlines.map(x=>({id:x.id,title:x.title,description:x.description,dueDate:x.dueDate.toISOString().slice(0,10),dueTime:x.dueTime||undefined,priority:x.priority,status:x.status,category:x.category,assigneeId:x.assigneeId,notifyIds:x.notifyIds,recurrence:x.recurrence,reminders:x.reminders,notes:x.notes,waitingFor:x.waitingFor,requireRead:x.requireRead,checklist:x.checklist as unknown as Database["deadlines"][number]["checklist"],links:x.links,takenAt:x.takenAt?.toISOString(),completedAt:x.completedAt?.toISOString(),deletedAt:x.deletedAt?.toISOString(),createdAt:x.createdAt.toISOString(),updatedAt:x.updatedAt.toISOString(),audits:x.auditLogs.map(a=>({id:a.id,at:a.createdAt.toISOString(),actor:a.actor?.name||"Sistema",action:a.action,detail:a.detail||undefined}))}))}}
export async function readDb():Promise<Database>{if(process.env.DATABASE_URL)return readPostgres();try{return JSON.parse(await fs.readFile(file,"utf8"))}catch{const db=createSeed();await fs.mkdir(path.dirname(file),{recursive:true});await fs.writeFile(file,JSON.stringify(db,null,2));return db}}
async function persistPostgres(db:Database){const {prisma}=await import("./prisma");await prisma.$transaction(async tx=>{for(const u of db.users)await tx.user.upsert({where:{id:u.id},update:{name:u.name,email:u.email,role:u.role,color:u.color},create:{...u,passwordHash:"bootstrap-via-env"}});for(const d of db.deadlines){await tx.deadLine.upsert({where:{id:d.id},update:{title:d.title,description:d.description,dueDate:new Date(`${d.dueDate}T12:00:00Z`),dueTime:d.dueTime,priority:d.priority,status:d.status,category:d.category,assigneeId:d.assigneeId,notifyIds:d.notifyIds,recurrence:d.recurrence,reminders:d.reminders,notes:d.notes,waitingFor:d.waitingFor,requireRead:d.requireRead,checklist:d.checklist,links:d.links,takenAt:d.takenAt?new Date(d.takenAt):null,completedAt:d.completedAt?new Date(d.completedAt):null,deletedAt:d.deletedAt?new Date(d.deletedAt):null},create:{id:d.id,title:d.title,description:d.description,dueDate:new Date(`${d.dueDate}T12:00:00Z`),dueTime:d.dueTime,priority:d.priority,status:d.status,category:d.category,assigneeId:d.assigneeId,notifyIds:d.notifyIds,recurrence:d.recurrence,reminders:d.reminders,notes:d.notes,waitingFor:d.waitingFor,requireRead:d.requireRead,checklist:d.checklist,links:d.links,takenAt:d.takenAt?new Date(d.takenAt):null,completedAt:d.completedAt?new Date(d.completedAt):null,deletedAt:d.deletedAt?new Date(d.deletedAt):null}});for(const a of d.audits)await tx.auditLog.upsert({where:{id:a.id},update:{action:a.action,detail:a.detail},create:{id:a.id,deadlineId:d.id,actorId:db.users.find(u=>u.name===a.actor)?.id,action:a.action,detail:a.detail,createdAt:new Date(a.at)}})}})}
export async function updateDb<T>(fn:(db:Database)=>T|Promise<T>):Promise<T>{let result!:T;queue=queue.then(async()=>{const db=await readDb();result=await fn(db);if(process.env.DATABASE_URL)await persistPostgres(db);else await fs.writeFile(file,JSON.stringify(db,null,2))});await queue;return result}
